### ISSUE TITLE
Use --containall and user specific tmp directory for singularity call

### ISSUE THREAD

**Issue by jsmedmar** [leukgen/toil_container#15]
We need to do something like this, so that every container call uses a new tmp directory:

`--workdir $TMP_DIR/${USER}_toi_container_`openssl rand -hex 12` \`

Perhaps cleaning tmp afterwards?

We also need to use `--containall` so that `$HOME` is not mapped inside the container

**Comment by juanesarango** [comment]
Is this issue related with #16?

**Comment by jsmedmar** [comment]
yep, it seems you can resolve issues if you write `resolves #id` in the commit
